# Generated by Django 2.0.2 on 2018-02-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=191, unique=True)),
                ('platform', models.CharField(default=None, max_length=50)),
                ('type', models.CharField(max_length=191)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('archived', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=50)),
            ],
        ),
    ]
