# Generated by Django 2.0.2 on 2018-02-23 04:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channel',
            name='platform',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=60, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
