# Generated by Django 2.0.2 on 2018-02-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_auto_20180223_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='channel',
            name='platform',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
