# Generated by Django 2.0.2 on 2018-02-17 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user',
            new_name='owner',
        ),
    ]
