# Generated by Django 2.0.2 on 2018-03-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180228_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='activation_link_sent_at',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='activation_link',
            new_name='email_activation_link',
        ),
        migrations.RemoveField(
            model_name='user',
            name='signed_up_with',
        ),
        migrations.AddField(
            model_name='user',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='email_activation_link_sent_at',
            field=models.DateTimeField(null=True),
        ),
    ]
